### ISSUE TITLE
TypeError: object list can't be used in 'await' expression

### ISSUE THREAD

**Issue by schro-j** [UltimaHoarder/UltimaScraper#1633]
whole lot of errors but thats the lasst one

here is the rest if youre interested 

 | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\Downloads\OnlyFans-7.4.1_2\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\josh_\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Downloads\OnlyFans-7.4.1_2\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Downloads\OnlyFans-7.4.1_2\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "D:\Downloads\OnlyFans-7.4.1_2\OnlyFans-7.4.1\modules\onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
  File "C:\Users\josh_\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\josh_\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\josh_\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\josh_\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
TypeError: object list can't be used in 'await' expression

**Comment by americanseeder1865** [comment]
@LunarPenguin What's weird is that you run this in a container and it works like a charm.

**Comment by francisafu** [comment]
@americanseeder1865 Thank you for that, what is funny is that, after I found that "bug" ,I traced back and found the change of "suit the stdlib something" in tqdm, so I'd like to make a pull request of those changes like " *task " in  OnlyFun's code, however I found that the Author team have already fixed it...lol.

**Comment by americanseeder1865** [comment]
Do it here https://github.com/DIGITALCRIMINALS/OnlyFans
