### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by mmg-and-campus** [UltimaHoarder/UltimaScraper#2012]
**CMD Result:**
`
D:\MyDowns\UltimaScraper-main>poetry run python start_us.py
__user_data__\profiles\OnlyFans\default\auth.json has been created. Fill in the relevant details and then press enter to continue.
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
1
Choose Profiles: 0 = All | 1 = default
1
Traceback (most recent call last):
  File "D:\MyDowns\UltimaScraper-main\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\90530\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\90530\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90530\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\MyDowns\UltimaScraper-main\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "D:\MyDowns\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "D:\MyDowns\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 88, in start_datascraper
    setup, _subscriptions = await datascraper.account_setup(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90530\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-g9b53nK5-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 415, in account_setup
    auth.auth_details.email
    ^^^^^^^^^^^^^^^^^
AttributeError: 'AuthModel' object has no attribute 'auth_details'. Did you mean: 'get_auth_details'?
`

**auth.json** in **default** folder :
`
{
  "auth": {
    "id": my_auth_id,
    "username": "default",
    "cookie": "auth_id=my_auth_id; sess=my_session_id; auth_hash=; auth_uniq_my_auth_id=; auth_uid_my_auth_id=;",
    "x_bc": "my_x_bc_id",
    "user_agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36",
    "email": "",
    "password": "",
    "hashed": false,
    "support_2fa": true,
    "active": true
  }
}
`

when i copy and paste my cookie, x_bc and user_agent i am getting error. 
i changed `"active": false` to `"active": true` (but still doing `false` after running program)

**Comment by johnfakidis** [comment]
Found a solution:
https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/1008

Basically copy paste the whole cookie

**Comment by hawktank** [comment]
Also be sure to copy "Cookie" from Request Headers don't copy values from "Set-Cookie" under Response Headers.  Easy mistake for those less familiar, these are not the same.  Also set "active: true" in the auth file, sometimes it's set to false automatically if there were previous auth errors encountered.
