### ISSUE TITLE
option["fromUser"]["id"] NoneType object is not subscriptable

### ISSUE THREAD

**Issue by anon767346** [UltimaHoarder/UltimaScraper#2017]
```
Traceback (most recent call last):
  File "E:\scrap\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\scrap\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "E:\scrap\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "E:\scrap\ultima_scraper\ultima_scraper.py", line 135, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-lHmDMN1p-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 109, in configure_datascraper_jobs
    chat_users = await self.get_chat_users()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-lHmDMN1p-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 427, in get_chat_users
    chats = await authed.get_chats()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-lHmDMN1p-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 260, in get_chats
    result["lastMessage"] = create_message(
                            ^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-lHmDMN1p-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\message_model.py", line 14, in __init__
    author = user.get_authed().find_user_by_identifier(option["fromUser"]["id"])
                                                       ~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by naodrej** [comment]
getting the same error, not sure how to fix this

**Comment by crazyrayjr** [comment]
Set the messages flag to false in config.js

![image](https://github.com/UltimaHoarder/UltimaScraper/assets/12072457/fa16156e-478e-4582-b145-eecbc26af812)

**Comment by Egon099** [comment]
get sess, user agent and x-bc from firefox. Chromium ones seem to fail for some reason
