### ISSUE TITLE
Scraper crashes when "OnlyFans" option 1 is selected

### ISSUE THREAD

**Issue by xxtensazenxx** [UltimaHoarder/UltimaScraper#2023]
I set up the script according to the guide. 
I set up the auth , and try to run the program. I select option 1 & it spits out this error 

`Traceback (most recent call last):
  File "C:\Users\frank\Desktop\UltimaScraper-main\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\frank\Desktop\UltimaScraper-main\start_us.py", line 44, in main
    _api = await USR.start(
  File "C:\Users\frank\Desktop\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "C:\Users\frank\Desktop\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 67, in start_datascraper
    await self.process_profiles(api, global_settings)
  File "C:\Users\frank\Desktop\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 166, in process_profiles
    temp_json_auth = main_helper.import_json(user_auth_filepath)
  File "C:\Users\frank\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-7RqfISuh-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 170, in import_json
    json_file = orjson.loads(o_file.read())
orjson.JSONDecodeError: unexpected character: line 3 column 11 (char 24)`

Anyone have any ideas? or is the script just dead?

**Comment by xxtensazenxx** [comment]
Fixed it- Changed the OF config.
"id':null," 
that fixed it

**Comment by butzen0** [comment]
I changed this and it didn't fix it
