### ISSUE TITLE
Ultimate_scrapper_collection issue

### ISSUE THREAD

**Issue by jakealves33** [UltimaHoarder/UltimaScraper#2034]
After installting poetry, when i try to start.py, it shows this error :- poetry run python start_us.py                           
Traceback (most recent call last):
  File "/home/mavrick/Downloads/UltimaScraper-main/start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "/home/mavrick/Downloads/UltimaScraper-main/tests/main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'
,

and when i try to install the ultima_scraper_collection from pip install git+https://github.com/UltimaScraper/UltimaScraper" then it asks for username and password, please solve this

**Comment by kadircorrea** [comment]
same error. :(

**Comment by selks213** [comment]
run `python updater.py`

**Comment by mian196** [comment]
> run `python updater.py`

i tried this but still i got the same error
