### ISSUE TITLE
TypeError: get_config() missing 1 required positional argument: 'config_class'

### ISSUE THREAD

**Issue by DrMcCoy** [UltimaHoarder/UltimaScraper#2035]
```
Traceback (most recent call last):
  File "OnlyFans/start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "main_test.py", line 27, in check_start_up
    check_config(fsm.settings_directory)
  File "tests/main_test.py", line 35, in check_config
    json_config, _updated = main_helper.get_config(config_path)
TypeError: get_config() missing 1 required positional argument: 'config_class'
```

Seems to be related to the change here? https://github.com/DIGITALCRIMINAL/UltimaScraperAPI/commit/125935c6c7409238cb4a748ab6a6dc0f34196cf0

I see why it doesn't work, but I don't see how it supposed to be working in the first place. Just passing make_settings.Config as config_class (which is essentially what the code previously used, if I understand correctly) doesn't work either, because that one doesn't have a json attribute.

I can't downgrade to any version of ultima_scraper_collection and ultima_scraper_api previous to that change either (i.e. to 1.1.3), because that one is missing auth stuff UltimateScraper seems to use now.

Like I said, I don't see how this is supposed to be working at all.

**Comment by Coding-FF** [comment]
I have the same problem. Is there anyone can sovle it?
