### ISSUE TITLE
Account recognized but I get: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by lanzjose** [UltimaHoarder/UltimaScraper#2043]
Hi everyone! So the program recognizes my username, my subscriptions and everything. But as soon as i choosse an account to download its content, I get this error. What can be the cause?

Traceback (most recent call last):
  File "C:\UltimaScraper\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\ME\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\UltimaScraper\start_us.py", line 44, in main
    _api = await USR.start(
  File "C:\UltimaScraper\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "C:\UltimaScraper\ultima_scraper\ultima_scraper.py", line 135, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
  File "C:\Users\ME\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-hof4bvgL-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 109, in configure_datascraper_jobs
    chat_users = await self.get_chat_users()
  File "C:\Users\ME\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-hof4bvgL-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 427, in get_chat_users
    chats = await authed.get_chats()
  File "C:\Users\ME\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-hof4bvgL-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 260, in get_chats
    result["lastMessage"] = create_message(
  File "C:\Users\ME\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-hof4bvgL-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\message_model.py", line 14, in __init__
    author = user.get_authed().find_user_by_identifier(option["fromUser"]["id"])
TypeError: 'NoneType' object is not subscriptable
PS C:\UltimaScraper>

**Comment by felixtheant** [comment]
I found an old issue log which mentions disabling the messages scrap job in the config.json file. 

Tested and it works for me.

**Comment by Egon099** [comment]
get sess, user agent and x-bc from firefox. Chromium ones seem to fail for some reason

**Comment by kotori2** [comment]
The issue is due to the chat list limit being too large.
Change the file `apis\onlyfans\classes\message_model.py` line 235
```python
    async def get_chats(
        self,
        links: list[str] = [],
        limit: int = 20,
        offset: int = 0,
        depth: int = 1,
        refresh: bool = True,
    ) -> list[dict[str, Any]]:
```

**Comment by haughingtrust** [comment]
> The issue is due to the chat list limit being too large. Change the file `apis\onlyfans\classes\message_model.py` line 235
> 
> ```python
>     async def get_chats(
>         self,
>         links: list[str] = [],
>         limit: int = 20,
>         offset: int = 0,
>         depth: int = 1,
>         refresh: bool = True,
>     ) -> list[dict[str, Any]]:
> ```

I believe you meant `apis\onlyfans\classes\auth_model.py`
