### ISSUE TITLE
Can't start "start_us.py"

### ISSUE THREAD

**Issue by Yetdel** [UltimaHoarder/UltimaScraper#2052]
I have this Error  when i start the scrapper.

   File "E:\download\UltimaScraper-main\start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "E:\download\UltimaScraper-main\tests\main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'

I already used the "update.py" but i still get the same error does anyone know how to fix it ? 

edit: Typo

**Comment by illusionistsquirrel** [comment]
A few other people were having this problem - myself included - and each issue ticket has been ignored or forgotten by the dev so far. Hoep you find a solution, do share here if you do.

**Comment by Nveatch** [comment]
That means the environment poetry is using is missing that module. Try this:
1. Open an admin powershell/cmd window in the ultima scraper folder ( containing pyproject.toml)
2. type 'poetry update'

That'll crosscheck the packages in the .toml file against what you have installed, and should install that module. then try:

3. poetry run python start_us.py

**Comment by cyberkoala** [comment]
> That means the environment poetry is using is missing that module. Try this:
> 
> 1. Open an admin powershell/cmd window in the ultima scraper folder ( containing pyproject.toml)
> 2. type 'poetry update'
> 
> That'll crosscheck the packages in the .toml file against what you have installed, and should install that module. then try:
> 
> 3. poetry run python start_us.py

Issue that i run into here was this: 

The lock file is not compatible with the current version of Poetry.
Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command."

Not sure how we got to this state, but i had to delete the old poetry lock before updating poetry, then could run it.

**Comment by Malurth** [comment]
meanwhile I can't get it to work because poetry update command fails due to using a too-recent version of python. can't figure out how to get it to use other versions. tried uninstalling 3.12, setting path variables, and doing a fresh reinstall of damn near everything and I get blocked when trying to reinstall poetry because it can't find Python312/python.exe. thing seems dead-set on using the wrong version of python :/

edit: ok got it to work by reinstalling poetry via curl; still said wrong python version but I used "poetry env use" to point to the 3.11 executable

**Comment by Nveatch** [comment]
ha, was just writing that, to use env use. But yeah, looks like poetry doesn't support 3.12 yet, and since I've been having multiple issues with it, ended up rolling back to 3.11 personally.

**Comment by dummythicc99** [comment]
> That means the environment poetry is using is missing that module. Try this:
> 
> 1. Open an admin powershell/cmd window in the ultima scraper folder ( containing pyproject.toml)
> 2. type 'poetry update'
> 
> That'll crosscheck the packages in the .toml file against what you have installed, and should install that module. then try:
> 
> 3. poetry run python start_us.py

Tried this but I keep getting the same error as when I run `python updater.py`, which is:

`C:\Users\mtpet\Downloads\UltimaScraper-main\UltimaScraper-main>poetry update
Updating dependencies
Resolving dependencies... (1.6s)

Package operations: 20 installs, 6 updates, 0 removals

  • Updating multidict (6.0.4 -> 6.0.5): Failed

  CalledProcessError

  Command '['C:\\Users\\mtpet\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\ultima-scraper-mNpUdkaP-py3.11\\Scripts\\python.exe', '-m', 'pip', 'uninstall', 'multidict', '-y']' returned non-zero exit status 1.

  at C:\Program Files\Python311\Lib\subprocess.py:571 in run
       567│             # We don't call process.wait() as .__exit__ does that for us.
       568│             raise
       569│         retcode = process.poll()
       570│         if check and retcode:
    →  571│             raise CalledProcessError(retcode, process.args,
       572│                                      output=stdout, stderr=stderr)
       573│     return CompletedProcess(process.args, retcode, stdout, stderr)
       574│
       575│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['C:\\Users\\mtpet\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\ultima-scraper-mNpUdkaP-py3.11\\Scripts\\python.exe', '-m', 'pip', 'uninstall', 'multidict', '-y'] errored with the following return code 1

  Output:
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "C:\Users\mtpet\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-mNpUdkaP-py3.11\Lib\site-packages\pip\__main__.py", line 22, in <module>
      from pip._internal.cli.main import main as _main
    File "C:\Users\mtpet\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-mNpUdkaP-py3.11\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "C:\Users\mtpet\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-mNpUdkaP-py3.11\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "C:\Users\mtpet\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-mNpUdkaP-py3.11\Lib\site-packages\pip\_internal\cli\main_parser.py", line 10, in <module>
      from pip._internal.cli import cmdoptions
    File "C:\Users\mtpet\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-mNpUdkaP-py3.11\Lib\site-packages\pip\_internal\cli\cmdoptions.py", line 29, in <module>
      from pip._internal.models.target_python import TargetPython
  ModuleNotFoundError: No module named 'pip._internal.models.target_python'


  at ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry\utils\env\base_env.py:354 in _run
      350│                 output = subprocess.check_output(
      351│                     cmd, stderr=stderr, env=env, text=True, **kwargs
      352│                 )
      353│         except CalledProcessError as e:
    → 354│             raise EnvCommandError(e)
      355│
      356│         return output
      357│
      358│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

Cannot install multidict.`
