### ISSUE TITLE
Fansly Issue

### ISSUE THREAD

**Issue by TyranicalJim** [UltimaHoarder/UltimaScraper#2055]
I'm having some issues with the fansly script I get the following when trying to run it: 

`Traceback (most recent call last):
  File "C:\Users\insan\Documents\Shortcuts\UltimaScraper-main\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\insan\Documents\Shortcuts\UltimaScraper-main\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\insan\Documents\Shortcuts\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "C:\Users\insan\Documents\Shortcuts\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 67, in start_datascraper
    await self.process_profiles(api, global_settings)
  File "C:\Users\insan\Documents\Shortcuts\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 166, in process_profiles
    temp_json_auth = main_helper.import_json(user_auth_filepath)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\insan\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-3a-OLhAn-py3.11\Lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 170, in import_json
    json_file = orjson.loads(o_file.read())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 5 column 153 (char 202)`

I've recently had to rebuild my PC so all installs are completely fresh. Onlyfans script is running without issue.

**Comment by TyranicalJim** [comment]
I've closed this, on closer inspection I realised I screwed up the authorisation bit 

Error = PEBCAK
