### ISSUE TITLE
ModuleNotFoundError: No module named 'ultima_scraper_collection'

### ISSUE THREAD

**Issue by raleighlittles** [UltimaHoarder/UltimaScraper#2063]
Trying to install this on Ubuntu 23.10, running Python version Python 3.11.6.

I have poetry installed: 

![image](https://github.com/UltimaHoarder/UltimaScraper/assets/2137201/fde21b79-e511-4edd-820d-2eb4ace9a015)

But when I try to run the tool itself like it says:

```bash
$ poetry run python start_us.py
```

I get this error

```
Traceback (most recent call last):
  File "/home/raleigh/Downloads/UltimaScraper/start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "/home/raleigh/Downloads/UltimaScraper/tests/main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'

```

**Comment by joaogutierrre** [comment]
Did you run: `python updater.py` before running `$ poetry run python start_us.py` ?

**Comment by EolGraymane** [comment]
I too am getting this error, Windows pleb though so use the syntax py insead of python.
Running 3.11.9
Poetry installed and updated
Ran the updater twice just to make sure.
Even downloaded the API and extracted the zip to the Python scripts directory.
PS C:\Scripts\UltimaScraper-main> py .\updater.py
Updating dependencies
Resolving dependencies... (1.9s)

No dependencies to install or update

Writing lock file
Script has been updated, exiting in 5 seconds
PS C:\Scripts\UltimaScraper-main> py .\updater.py
Updating dependencies
Resolving dependencies... (1.8s)

No dependencies to install or update

Writing lock file
Script has been updated, exiting in 5 seconds
PS C:\Scripts\UltimaScraper-main> poetry run py start_us.py
Traceback (most recent call last):
  File "C:\Scripts\UltimaScraper-main\start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "C:\Scripts\UltimaScraper-main\tests\main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'

**Comment by dummythicc99** [comment]
> I too am getting this error, Windows pleb though so use the syntax py insead of python. Running 3.11.9 Poetry installed and updated Ran the updater twice just to make sure. Even downloaded the API and extracted the zip to the Python scripts directory. PS C:\Scripts\UltimaScraper-main> py .\updater.py Updating dependencies Resolving dependencies... (1.9s)
> 
> No dependencies to install or update
> 
> Writing lock file Script has been updated, exiting in 5 seconds PS C:\Scripts\UltimaScraper-main> py .\updater.py Updating dependencies Resolving dependencies... (1.8s)
> 
> No dependencies to install or update
> 
> Writing lock file Script has been updated, exiting in 5 seconds PS C:\Scripts\UltimaScraper-main> poetry run py start_us.py Traceback (most recent call last): File "C:\Scripts\UltimaScraper-main\start_us.py", line 13, in main_test.check_start_up() File "C:\Scripts\UltimaScraper-main\tests\main_test.py", line 21, in check_start_up from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager ModuleNotFoundError: No module named 'ultima_scraper_collection'

Just run ofscraper by datawhores. It's much easier to set up and there's a discord where you can get some actual support

**Comment by raleighlittles** [comment]
> > I too am getting this error, Windows pleb though so use the syntax py insead of python. Running 3.11.9 Poetry installed and updated Ran the updater twice just to make sure. Even downloaded the API and extracted the zip to the Python scripts directory. PS C:\Scripts\UltimaScraper-main> py .\updater.py Updating dependencies Resolving dependencies... (1.9s)
> > No dependencies to install or update
> > Writing lock file Script has been updated, exiting in 5 seconds PS C:\Scripts\UltimaScraper-main> py .\updater.py Updating dependencies Resolving dependencies... (1.8s)
> > No dependencies to install or update
> > Writing lock file Script has been updated, exiting in 5 seconds PS C:\Scripts\UltimaScraper-main> poetry run py start_us.py Traceback (most recent call last): File "C:\Scripts\UltimaScraper-main\start_us.py", line 13, in main_test.check_start_up() File "C:\Scripts\UltimaScraper-main\tests\main_test.py", line 21, in check_start_up from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager ModuleNotFoundError: No module named 'ultima_scraper_collection'
> 
> Just run ofscraper by datawhores. It's much easier to set up and there's a discord where you can get some actual support

Thanks, I'll check it out.
