### ISSUE TITLE
TypeError: 'ClientConnectionError' object is not iterable

### ISSUE THREAD

**Issue by bezaaas** [UltimaHoarder/UltimaScraper#2070]
Hello,

I started it and went to sleep, when I woke up I saw this

Processing Download:
Name: model | Type: Messages | Downloading: 1 | Total: 1 | Duplicates: 0 | Directory: E:\OnlyFans\model

Traceback (most recent call last):
  File "C:\UltimaScraper-main\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\UltimaScraper-main\start_us.py", line 44, in main
    _api = await USR.start(
  File "C:\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "C:\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 137, in start_datascraper
    await datascraper.datascraper.api.job_manager.process_jobs()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-xmNAmSo9-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 45, in process_jobs
    await asyncio.create_task(self.__worker())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-xmNAmSo9-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 53, in __worker
    await job.task
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-xmNAmSo9-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 171, in prepare_scraper
    temp_master_set = await self.datascraper.get_all_posts(user)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-xmNAmSo9-py3.10\lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 102, in get_all_posts
    temp_master_set = await subscription.get_posts()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-xmNAmSo9-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\user_model.py", line 308, in get_posts
    results = await self.scrape_manager.bulk_scrape(links)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-xmNAmSo9-py3.10\lib\site-packages\ultima_scraper_api\managers\scrape_manager.py", line 19, in bulk_scrape
    final_result = list(chain(*result))
TypeError: 'ClientConnectionError' object is not iterable

**Comment by Egon099** [comment]
get sess, user agent and x-bc from firefox. Chromium ones seem to fail for some reason
