### ISSUE TITLE
keyerror: 'data'

### ISSUE THREAD

**Issue by butzen0** [UltimaHoarder/UltimaScraper#2086]
every time I try to run it, this error appears

PS E:\old OF\UltimaScraper-main> poetry run python start_us.py
Traceback (most recent call last):
  File "E:\old OF\UltimaScraper-main\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\old OF\UltimaScraper-main\start_us.py", line 44, in main
    _api = await USR.start(
  File "E:\old OF\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "E:\old OF\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 67, in start_datascraper
    await self.process_profiles(api, global_settings)
  File "E:\old OF\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 171, in process_profiles
    authed = await api.login(json_auth)
  File "C:\Users\willi\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-SvDIuQBW-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\onlyfans.py", line 38, in login
    authed.issues = issues if issues["data"] else None
KeyError: 'data'

**Comment by adelh1de** [comment]
@butzen0 can you provide a solution on how you resolved this ? Stuck at the same error after a reinstallation

**Comment by adelh1de** [comment]
Nevermind. The problem was reusing the auth.json from an older version. Found the error using the debugger

**Comment by butzen0** [comment]
> Deixa para lá. O problema era reutilizar o auth.json de uma versão mais antiga. Encontrou o erro usando o depurador

Same thing, I made the same mistake
