### ISSUE TITLE
Crash right after login

### ISSUE THREAD

**Issue by MarioVilas** [UltimaHoarder/UltimaScraper#2092]
```
Traceback (most recent call last):
  File "/home/parallels/UltimaScraper/start_us.py", line 62, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/parallels/UltimaScraper/start_us.py", line 44, in main
    _api = await USR.start(
  File "/home/parallels/UltimaScraper/ultima_scraper/ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "/home/parallels/UltimaScraper/ultima_scraper/ultima_scraper.py", line 88, in start_datascraper
    setup, _subscriptions = await datascraper.account_setup(
  File "/home/parallels/.cache/pypoetry/virtualenvs/ultima-scraper-QnDTDjBS-py3.10/lib/python3.10/site-packages/ultima_scraper_collection/modules/module_streamliner.py", line 415, in account_setup
    auth.auth_details.email
AttributeError: 'AuthModel' object has no attribute 'auth_details'. Did you mean: 'get_auth_details'?
```

**Comment by Nairelaav** [comment]
I had the same issue today, this comment solved it for me: https://github.com/UltimaHoarder/UltimaScraper/issues/2054#issuecomment-1870109267

**Comment by ghost** [comment]
Just use OFscraper https://github.com/datawhores/OF-Scraper
