### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by meanjoep92** [UltimaHoarder/UltimaScraper#2100]
```
Traceback (most recent call last):
  File "C:\Users\sloopjohnb\Downloads\ArchivedUltimaScraper-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\sloopjohnb\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\sloopjohnb\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\sloopjohnb\Downloads\ArchivedUltimaScraper-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\sloopjohnb\Downloads\ArchivedUltimaScraper-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\sloopjohnb\Downloads\ArchivedUltimaScraper-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\sloopjohnb\Downloads\ArchivedUltimaScraper-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\sloopjohnb\Downloads\ArchivedUltimaScraper-7.6.1\modules\onlyfans.py", line 824, in prepare_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Users\sloopjohnb\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\sloopjohnb\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\sloopjohnb\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 575, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\sloopjohnb\AppData\Roaming\Python\Python310\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\Users\sloopjohnb\Downloads\ArchivedUltimaScraper-7.6.1\modules\onlyfans.py", line 1128, in media_scraper
    if int(media_id) in new_post["preview_media_ids"]:
TypeError: argument of type 'NoneType' is not iterable
```

Been using an older version that's worked for years, simply because of the progress bar...

It's been working fine for the past few days but suddenly got this.

**Comment by ESMP** [comment]
Same here, was working fine just yesterday :(

**Comment by hojotis** [comment]
Is it solved? I also encountered the same problem

**Comment by naodrej** [comment]
Anyone figured how to fix this?

**Comment by jrgdiaz** [comment]
I'm having the same issue on Mac using Python 3.11.5, also tested on Windows with Python 3.11.5 and code runs fine.
