### ISSUE TITLE
Some help with tracebacks

### ISSUE THREAD

**Issue by dildosven** [UltimaHoarder/UltimaScraper#2106]
Can just start the scraper and this comes up. When I have auto choice turned off, I can choose onlyfans and profile then this

Traceback (most recent call last):
  File "D:\PADA\Onlyfans\UltimaScraper-main\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\MYNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\MYNAME\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\PADA\Onlyfans\UltimaScraper-main\start_us.py", line 44, in main
    _api = await USR.start(
  File "D:\PADA\Onlyfans\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "D:\PADA\Onlyfans\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 67, in start_datascraper
    await self.process_profiles(api, global_settings)
  File "D:\PADA\Onlyfans\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 166, in process_profiles
    temp_json_auth = main_helper.import_json(user_auth_filepath)
  File "C:\Users\MYNAME\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-KNzGJp-n-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 170, in import_json
    json_file = orjson.loads(o_file.read())
orjson.JSONDecodeError: invalid literal: line 12 column 15 (char 909)

Any help appreciated!

[config.json](https://github.com/user-attachments/files/15825896/config.json)

**Comment by haughingtrust** [comment]
`temp_json_auth = main_helper.import_json(user_auth_filepath)`
I believe this is a formatting error in your `auth.json` file

**Comment by dildosven** [comment]
Thanks! Helped

Things I did to fix:
1. Deleted the auth.json
2. python updater.py
3. poetry run python start_us.py
4. Used sess, user agent and x-bc from firefox (https://github.com/UltimaHoarder/UltimaScraper/issues/2070)
5. Changed the config.json. Changed the dynamic_rules_link to "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json"
6. Changed the onlyfans messages and paid contents to false (https://github.com/UltimaHoarder/UltimaScraper/issues/2058)
7. And changed the auto_media_choice to "All" (https://github.com/UltimaHoarder/UltimaScraper/issues/2041)
