### ISSUE TITLE
Confused about Fansly info

### ISSUE THREAD

**Issue by ElSenorIncognito** [UltimaHoarder/UltimaScraper#2107]
Based on what I've seen in other issues the following error seems to be an issue with the auth info. I could be wrong but the tutorial doesn't show how to get the Fansly info only the OnlyFans info. 

```Traceback (most recent call last):
  File "/mnt/nvme1/UltimaScraper/start_us.py", line 62, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/mnt/nvme1/UltimaScraper/start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "/mnt/nvme1/UltimaScraper/ultima_scraper/ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "/mnt/nvme1/UltimaScraper/ultima_scraper/ultima_scraper.py", line 88, in start_datascraper
    setup, _subscriptions = await datascraper.account_setup(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvme1/UltimaScraper/venv/lib/python3.11/site-packages/ultima_scraper_collection/modules/module_streamliner.py", line 409, in account_setup
    await datascraper.manage_subscriptions(
  File "/mnt/nvme1/UltimaScraper/venv/lib/python3.11/site-packages/ultima_scraper_collection/modules/module_streamliner.py", line 359, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvme1/UltimaScraper/venv/lib/python3.11/site-packages/ultima_scraper_collection/managers/datascraper_manager/datascrapers/fansly.py", line 123, in get_all_subscriptions
    subscriptions = await authed.get_subscriptions(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvme1/UltimaScraper/venv/lib/python3.11/site-packages/ultima_scraper_api/apis/fansly/classes/auth_model.py", line 238, in get_subscriptions
    subscriptions: list[SubscriptionModel] = await asyncio.gather(*tasks)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvme1/UltimaScraper/venv/lib/python3.11/site-packages/ultima_scraper_api/apis/fansly/classes/auth_model.py", line 228, in assign_user_to_sub
    user = await self.get_user(raw_subscription["accountId"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvme1/UltimaScraper/venv/lib/python3.11/site-packages/ultima_scraper_api/apis/fansly/classes/auth_model.py", line 133, in get_user
    response = create_user(response["response"][0], self)
                           ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Gitoilet** [comment]
Just noting I've been facing the same for some time. No idea of a fix yet.
